// <auto-generated />
namespace HpSubscriptions.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddContentType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddContentType));
        
        string IMigrationMetadata.Id
        {
            get { return "201512171352490_Add-Content-Type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
